# Generated by Django 4.1.7 on 2023-04-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_rename_bids_bid_rename_comments_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='image_url',
            new_name='category',
        ),
    ]
