# Generated by Django 4.1.7 on 2023-04-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_bid_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='isClosed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
