# Generated by Django 4.1.7 on 2023-04-26 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_listing_isclosed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='isClosed',
        ),
    ]
